create table public.reviews (
  id bigint generated by default as identity not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  to_user_id text not null,
  from_user_id text not null,
  ticket_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint reviews_pkey primary key (id),
  constraint reviews_to_user_id_fkey foreign key (to_user_id) references users (user_id),
  constraint reviews_from_user_id_fkey foreign key (from_user_id) references users (user_id),
  constraint reviews_ticket_id_fkey foreign key (ticket_id) references tickets (id),
  constraint unique_review unique (from_user_id, to_user_id)
);
