export const venues = [
  {
    id: 9,
    created_at: "2025-05-15 13:21:17.558335+00",
    venue_name: "Gurgaon Badminton Club, Sector 52, Wazirabad",
    image:
      "https://content.jdmagicbox.com/comp/gurgaon/k8/011pxx11.xx11.190122233414.a4k8/catalogue/gurgaon-badminton-club-gurgaon-qca7a5llvv.jpg",
    maps_link:
      "https://maps.app.goo.gl/3Yug1Jx9LWzWGzLQ8?g_st=com.google.maps.preview.copy",
    description:
      "Very good place to play badminton, location is a bit inside but nearby",
    location: "Wazirabad, Sector 52, Gurugram, Haryana 122003, India",
    subscription_models: [
      {
        title: "Weekend Pass (8)",
        price: 1300,
        billing: "8 Sessions",
        popular: false,
        features: ["Prebook your weekends"],
      },
      {
        title: "Pro Pass (12)",
        price: 1900,
        billing: "12 Sessions",
        popular: false,
        features: ["Slot carry forward if not used + Slot reservation"],
      },
      {
        title: "Elite Pass (16)",
        price: 2300,
        billing: "16 Sessions",
        popular: false,
        features: ["Slot reservation"],
      },
      {
        title: "Full month unlimited",
        price: 3499,
        billing: "Unlimited Sessions",
        popular: false,
        features: ["Unlimited court access"],
      },
      {
        title: "Duo pass (12)",
        price: 2700,
        billing: "12 Sessions for 2",
        popular: false,
        features: ["Enter the Duo Championship and Leadership"],
      },
      {
        title: "Squad pass (12)",
        price: 7000,
        billing: "12 Sessions for Group",
        popular: false,
        features: ["Enter the Squad Championship and Leadership"],
      },
    ],
  },
  {
    id: 12,
    created_at: "2025-06-25 10:30:38.921574+00",
    venue_name: "J.N.S Sports Academy",
    image:
      "https://media.hudle.in/venues/1b8125fa-26b5-467d-a2c4-4a832f5b2bb9/photo/4d49c0212186ffa997bd1a325452351657eddf82",
    maps_link:
      "https://maps.app.goo.gl/DGUhxRS3bSCXhknr7?g_st=com.google.maps.preview.copy",
    description: "Clean and aesthetic court with AC",
    location: "Samaspur Village, Sector 51, Gurugram, Haryana 122003, India",
    subscription_models: [
      {
        title: "Weekend Pass (8)",
        price: 1900,
        billing: "8 Sessions",
        popular: false,
        features: [
          "Prebook your weekends",
          "AC court access",
          "Premium equipment",
          "Locker facility",
        ],
      },
      {
        title: "Pro Pass (12)",
        price: 2800,
        billing: "12 Sessions",
        popular: true,
        features: [
          "Slot carry forward if not used",
          "Slot reservation",
          "Professional coaching",
          "Health tracking",
        ],
      },
      {
        title: "Elite Pass (16)",
        price: 3650,
        billing: "16 Sessions",
        popular: false,
        features: [
          "Slot reservation",
          "VIP court access",
          "Personal trainer sessions",
          "Nutrition consultation",
        ],
      },
      {
        title: "Full month unlimited",
        price: 4399,
        billing: "Unlimited Sessions",
        popular: false,
        features: [
          "Unlimited access",
          "Premium facilities",
          "Guest privileges",
          "Event invitations",
        ],
      },
      {
        title: "Duo pass (12)",
        price: 5500,
        billing: "12 Sessions for 2",
        popular: false,
        features: [
          "Enter the Duo Championship",
          "Leadership programs",
          "Couple training sessions",
          "Social events",
        ],
      },
      {
        title: "Squad pass (12)",
        price: 10000,
        billing: "12 Sessions for Group",
        popular: false,
        features: [
          "Enter the squad championship",
          "Team building activities",
          "Group coaching",
          "Corporate packages",
        ],
      },
    ],
  },
  {
    id: 1,
    created_at: "2025-07-06 12:00:00+00",
    venue_name: "Test Shuttle Zone, Sector 99, Imaginary Town",
    image: "https://via.placeholder.com/400x300.png?text=Test+Venue+Image",
    maps_link: "https://maps.app.goo.gl/fakeTestingVenue123",
    description:
      "This is a fake badminton court used strictly for testing. No shuttles were harmed.",
    location: "Sector 99, Imaginary Town, Nowhere State 000000",
    subscription_models: [
      {
        title: "Weekend Pass (8)",
        price: 2,
        billing: "8 Sessions",
        popular: false,
        features: ["Prebook your weekends"],
      },
      {
        title: "Pro Pass (12)",
        price: 2,
        billing: "12 Sessions",
        popular: false,
        features: ["Slot carry forward if not used + Slot reservation"],
      },
      {
        title: "Elite Pass (16)",
        price: 2,
        billing: "16 Sessions",
        popular: false,
        features: ["Slot reservation"],
      },
      {
        title: "Full month unlimited",
        price: 2,
        billing: "Unlimited Sessions",
        popular: false,
        features: ["Unlimited court access"],
      },
      {
        title: "Duo pass (12)",
        price: 2,
        billing: "12 Sessions for 2",
        popular: false,
        features: ["Enter the Duo Championship and Leadership"],
      },
      {
        title: "Squad pass (12)",
        price: 2,
        billing: "12 Sessions for Group",
        popular: false,
        features: ["Enter the Squad Championship and Leadership"],
      },
    ],
  },
];
