create table public."Orderitems" (
  id bigint generated by default as identity not null,
  order_id bigint null,
  ticket_id bigint null,
  quantity bigint null,
  sub_price text null,
  userid text null,
  status text null default 'confirmed'::text,
  used_premium_discount boolean null,
  userequipments jsonb null,
  constraint Orderitems_pkey primary key (id),
  constraint Orderitems_order_id_fkey foreign KEY (order_id) references orders (id),
  constraint Orderitems_ticket_id_fkey foreign KEY (ticket_id) references tickets (id),
  constraint Orderitems_userid_fkey foreign KEY (userid) references users (user_id)
) TABLESPACE pg_default;